/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request annul model
 * @export
 * @interface PayPhonePaymentButtonModelsCancellationSetRequestModel
 */
export interface PayPhonePaymentButtonModelsCancellationSetRequestModel {
    /**
     * Transaction id of sale to annul
     * @type {number}
     * @memberof PayPhonePaymentButtonModelsCancellationSetRequestModel
     */
    id: number;
}

/**
 * Check if a given object implements the PayPhonePaymentButtonModelsCancellationSetRequestModel interface.
 */
export function instanceOfPayPhonePaymentButtonModelsCancellationSetRequestModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function PayPhonePaymentButtonModelsCancellationSetRequestModelFromJSON(json: any): PayPhonePaymentButtonModelsCancellationSetRequestModel {
    return PayPhonePaymentButtonModelsCancellationSetRequestModelFromJSONTyped(json, false);
}

export function PayPhonePaymentButtonModelsCancellationSetRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhonePaymentButtonModelsCancellationSetRequestModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function PayPhonePaymentButtonModelsCancellationSetRequestModelToJSON(value?: PayPhonePaymentButtonModelsCancellationSetRequestModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

