/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PayPhoneButtonBusinessModelsLineItem } from '../models/PayPhoneButtonBusinessModelsLineItem';
import { PayPhoneISO8583ModelsPayPhoneBillTo } from '../models/PayPhoneISO8583ModelsPayPhoneBillTo';
import { HttpFile } from '../http/http';

export class PayPhoneButtonBusinessModelsOrder {
    'billTo'?: PayPhoneISO8583ModelsPayPhoneBillTo;
    'lineItems'?: Array<PayPhoneButtonBusinessModelsLineItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billTo",
            "baseName": "billTo",
            "type": "PayPhoneISO8583ModelsPayPhoneBillTo",
            "format": ""
        },
        {
            "name": "lineItems",
            "baseName": "lineItems",
            "type": "Array<PayPhoneButtonBusinessModelsLineItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsOrder.attributeTypeMap;
    }

    public constructor() {
    }
}

