/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayPhoneButtonBusinessModelsPassenger
 */
export interface PayPhoneButtonBusinessModelsPassenger {
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsPassenger
     */
    nationality?: string;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsPassenger interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsPassenger(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsPassengerFromJSON(json: any): PayPhoneButtonBusinessModelsPassenger {
    return PayPhoneButtonBusinessModelsPassengerFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsPassengerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsPassenger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'nationality': !exists(json, 'nationality') ? undefined : json['nationality'],
    };
}

export function PayPhoneButtonBusinessModelsPassengerToJSON(value?: PayPhoneButtonBusinessModelsPassenger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'status': value.status,
        'phone': value.phone,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'id': value.id,
        'email': value.email,
        'nationality': value.nationality,
    };
}

