/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PayPhoneButtonBusinessModelsTaxModel } from './PayPhoneButtonBusinessModelsTaxModel';
import {
    PayPhoneButtonBusinessModelsTaxModelFromJSON,
    PayPhoneButtonBusinessModelsTaxModelFromJSONTyped,
    PayPhoneButtonBusinessModelsTaxModelToJSON,
} from './PayPhoneButtonBusinessModelsTaxModel';

/**
 * Sale get model
 * @export
 * @interface PayPhoneButtonBusinessModelsSaleGetModel
 */
export interface PayPhoneButtonBusinessModelsSaleGetModel {
    /**
     * Customer email
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    email?: string;
    /**
     * Card type
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    cardType?: string;
    /**
     * External user identifier
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    clientUserId?: string;
    /**
     * Processor that served the request
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    processor?: string;
    /**
     * Card bin
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    bin?: string;
    /**
     * Últimos dígitos de la tarjeta
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    lastDigits?: string;
    /**
     * Deferred code
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    deferredCode?: string;
    /**
     * Deferred message
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    deferredMessage?: string;
    /**
     * Flag that indicate if the payment was deferred or not
     * @type {boolean}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    deferred?: boolean;
    /**
     * Card brand code Example (Visa 50)
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    cardBrandCode?: string;
    /**
     * Card brand
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    cardBrand?: string;
    /**
     * Amount charged (Number)
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    amount?: number;
    /**
     * Client transaction id
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    clientTransactionId?: string;
    /**
     * Customer phone number
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    phoneNumber?: string;
    /**
     * Transaction status code Example(1)
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    statusCode?: number;
    /**
     * Transaction status Example(Canceled)
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    transactionStatus?: string;
    /**
     * Authorization code emiting by bank, this field have value is transaction status was approved
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    authorizationCode?: string;
    /**
     * Message for error
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    message?: string;
    /**
     * Message code for the reason why transaction not approved
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    messageCode?: number;
    /**
     * PayPhone transaction id
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    transactionId?: number;
    /**
     * Customer Document id
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    document?: string;
    /**
     * Taxes apply to current transaction
     * @type {Array<PayPhoneButtonBusinessModelsTaxModel>}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    taxes?: Array<PayPhoneButtonBusinessModelsTaxModel>;
    /**
     * ISO code A of transaction currency
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    currency?: string;
    /**
     * Optional parameter 1
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    optionalParameter1?: string;
    /**
     * Optional parameter 2
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    optionalParameter2?: string;
    /**
     * Optional parameter 3
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    optionalParameter3?: string;
    /**
     * Optional parameter 4
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    optionalParameter4?: string;
    /**
     * Store name
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    storeName?: string;
    /**
     * Fecha en la que se realizo la transacción
     * @type {Date}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    date?: Date;
    /**
     * ISO code de la region de la tienda que recibió el pago
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    regionIso?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    transactionType?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    recap?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    reference?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayPhoneButtonBusinessModelsSaleGetModel
     */
    canBypassRedirection?: boolean;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsSaleGetModel interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsSaleGetModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsSaleGetModelFromJSON(json: any): PayPhoneButtonBusinessModelsSaleGetModel {
    return PayPhoneButtonBusinessModelsSaleGetModelFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsSaleGetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsSaleGetModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'cardType': !exists(json, 'cardType') ? undefined : json['cardType'],
        'clientUserId': !exists(json, 'clientUserId') ? undefined : json['clientUserId'],
        'processor': !exists(json, 'processor') ? undefined : json['processor'],
        'bin': !exists(json, 'bin') ? undefined : json['bin'],
        'lastDigits': !exists(json, 'lastDigits') ? undefined : json['lastDigits'],
        'deferredCode': !exists(json, 'deferredCode') ? undefined : json['deferredCode'],
        'deferredMessage': !exists(json, 'deferredMessage') ? undefined : json['deferredMessage'],
        'deferred': !exists(json, 'deferred') ? undefined : json['deferred'],
        'cardBrandCode': !exists(json, 'cardBrandCode') ? undefined : json['cardBrandCode'],
        'cardBrand': !exists(json, 'cardBrand') ? undefined : json['cardBrand'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'clientTransactionId': !exists(json, 'clientTransactionId') ? undefined : json['clientTransactionId'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'transactionStatus': !exists(json, 'transactionStatus') ? undefined : json['transactionStatus'],
        'authorizationCode': !exists(json, 'authorizationCode') ? undefined : json['authorizationCode'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'messageCode': !exists(json, 'messageCode') ? undefined : json['messageCode'],
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
        'document': !exists(json, 'document') ? undefined : json['document'],
        'taxes': !exists(json, 'taxes') ? undefined : ((json['taxes'] as Array<any>).map(PayPhoneButtonBusinessModelsTaxModelFromJSON)),
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'optionalParameter1': !exists(json, 'optionalParameter1') ? undefined : json['optionalParameter1'],
        'optionalParameter2': !exists(json, 'optionalParameter2') ? undefined : json['optionalParameter2'],
        'optionalParameter3': !exists(json, 'optionalParameter3') ? undefined : json['optionalParameter3'],
        'optionalParameter4': !exists(json, 'optionalParameter4') ? undefined : json['optionalParameter4'],
        'storeName': !exists(json, 'storeName') ? undefined : json['storeName'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'regionIso': !exists(json, 'regionIso') ? undefined : json['regionIso'],
        'transactionType': !exists(json, 'transactionType') ? undefined : json['transactionType'],
        'recap': !exists(json, 'recap') ? undefined : json['recap'],
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
        'canBypassRedirection': !exists(json, 'canBypassRedirection') ? undefined : json['canBypassRedirection'],
    };
}

export function PayPhoneButtonBusinessModelsSaleGetModelToJSON(value?: PayPhoneButtonBusinessModelsSaleGetModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'cardType': value.cardType,
        'clientUserId': value.clientUserId,
        'processor': value.processor,
        'bin': value.bin,
        'lastDigits': value.lastDigits,
        'deferredCode': value.deferredCode,
        'deferredMessage': value.deferredMessage,
        'deferred': value.deferred,
        'cardBrandCode': value.cardBrandCode,
        'cardBrand': value.cardBrand,
        'amount': value.amount,
        'clientTransactionId': value.clientTransactionId,
        'phoneNumber': value.phoneNumber,
        'statusCode': value.statusCode,
        'transactionStatus': value.transactionStatus,
        'authorizationCode': value.authorizationCode,
        'message': value.message,
        'messageCode': value.messageCode,
        'transactionId': value.transactionId,
        'document': value.document,
        'taxes': value.taxes === undefined ? undefined : ((value.taxes as Array<any>).map(PayPhoneButtonBusinessModelsTaxModelToJSON)),
        'currency': value.currency,
        'optionalParameter1': value.optionalParameter1,
        'optionalParameter2': value.optionalParameter2,
        'optionalParameter3': value.optionalParameter3,
        'optionalParameter4': value.optionalParameter4,
        'storeName': value.storeName,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'regionIso': value.regionIso,
        'transactionType': value.transactionType,
        'recap': value.recap,
        'reference': value.reference,
        'canBypassRedirection': value.canBypassRedirection,
    };
}

