/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Model for cancellation set
*/
export class PayPhoneButtonBusinessModelsCancellationSetModel {
    /**
    * Annul id for get transaction
    */
    'id'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsCancellationSetModel.attributeTypeMap;
    }

    public constructor() {
    }
}

