/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Sale model to response
 * @export
 * @interface PayPhoneButtonBusinessModelsSaleModel
 */
export interface PayPhoneButtonBusinessModelsSaleModel {
    /**
     * Identifier for current created transaction
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSaleModel
     */
    transactionId?: number;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsSaleModel interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsSaleModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsSaleModelFromJSON(json: any): PayPhoneButtonBusinessModelsSaleModel {
    return PayPhoneButtonBusinessModelsSaleModelFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsSaleModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsSaleModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
    };
}

export function PayPhoneButtonBusinessModelsSaleModelToJSON(value?: PayPhoneButtonBusinessModelsSaleModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactionId': value.transactionId,
    };
}

