/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Details of canceled sale
 * @export
 * @interface PayPhoneButtonBusinessModelsSale
 */
export interface PayPhoneButtonBusinessModelsSale {
    /**
     * Canceled sale id
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSale
     */
    id?: number;
    /**
     * Canceled sale status code
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsSale
     */
    statusCode?: number;
    /**
     * Canceled sale literal status
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSale
     */
    status?: string;
    /**
     * Client transaction id
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSale
     */
    clientTransactionId?: string;
    /**
     * Message for the cancelled transaction
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsSale
     */
    message?: string;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsSale interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsSale(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsSaleFromJSON(json: any): PayPhoneButtonBusinessModelsSale {
    return PayPhoneButtonBusinessModelsSaleFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsSaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsSale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'clientTransactionId': !exists(json, 'clientTransactionId') ? undefined : json['clientTransactionId'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function PayPhoneButtonBusinessModelsSaleToJSON(value?: PayPhoneButtonBusinessModelsSale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'statusCode': value.statusCode,
        'status': value.status,
        'clientTransactionId': value.clientTransactionId,
        'message': value.message,
    };
}

