/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PayPhoneButtonBusinessModelsPassenger } from './PayPhoneButtonBusinessModelsPassenger';
import {
    PayPhoneButtonBusinessModelsPassengerFromJSON,
    PayPhoneButtonBusinessModelsPassengerFromJSONTyped,
    PayPhoneButtonBusinessModelsPassengerToJSON,
} from './PayPhoneButtonBusinessModelsPassenger';

/**
 * 
 * @export
 * @interface PayPhoneButtonBusinessModelsLineItem
 */
export interface PayPhoneButtonBusinessModelsLineItem {
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    productName?: string;
    /**
     * 
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    unitPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    taxAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    productSKU?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    productDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    shippingDestinationTypes?: string;
    /**
     * 
     * @type {PayPhoneButtonBusinessModelsPassenger}
     * @memberof PayPhoneButtonBusinessModelsLineItem
     */
    passenger?: PayPhoneButtonBusinessModelsPassenger;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsLineItem interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsLineItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsLineItemFromJSON(json: any): PayPhoneButtonBusinessModelsLineItem {
    return PayPhoneButtonBusinessModelsLineItemFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsLineItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productName': !exists(json, 'productName') ? undefined : json['productName'],
        'unitPrice': !exists(json, 'unitPrice') ? undefined : json['unitPrice'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'totalAmount': !exists(json, 'totalAmount') ? undefined : json['totalAmount'],
        'taxAmount': !exists(json, 'taxAmount') ? undefined : json['taxAmount'],
        'productSKU': !exists(json, 'productSKU') ? undefined : json['productSKU'],
        'productDescription': !exists(json, 'productDescription') ? undefined : json['productDescription'],
        'shippingDestinationTypes': !exists(json, 'shippingDestinationTypes') ? undefined : json['shippingDestinationTypes'],
        'passenger': !exists(json, 'passenger') ? undefined : PayPhoneButtonBusinessModelsPassengerFromJSON(json['passenger']),
    };
}

export function PayPhoneButtonBusinessModelsLineItemToJSON(value?: PayPhoneButtonBusinessModelsLineItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productName': value.productName,
        'unitPrice': value.unitPrice,
        'quantity': value.quantity,
        'totalAmount': value.totalAmount,
        'taxAmount': value.taxAmount,
        'productSKU': value.productSKU,
        'productDescription': value.productDescription,
        'shippingDestinationTypes': value.shippingDestinationTypes,
        'passenger': PayPhoneButtonBusinessModelsPassengerToJSON(value.passenger),
    };
}

