/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayPhoneButtonBusinessModelsTaxModel
 */
export interface PayPhoneButtonBusinessModelsTaxModel {
    /**
     * Tax name
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsTaxModel
     */
    name?: string;
    /**
     * Tax amount charged the sum of value and tax field
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsTaxModel
     */
    amount?: number;
    /**
     * Tax value
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsTaxModel
     */
    value?: number;
    /**
     * Tax apply for current tax
     * @type {number}
     * @memberof PayPhoneButtonBusinessModelsTaxModel
     */
    tax?: number;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsTaxModel interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsTaxModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsTaxModelFromJSON(json: any): PayPhoneButtonBusinessModelsTaxModel {
    return PayPhoneButtonBusinessModelsTaxModelFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsTaxModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsTaxModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'tax': !exists(json, 'tax') ? undefined : json['tax'],
    };
}

export function PayPhoneButtonBusinessModelsTaxModelToJSON(value?: PayPhoneButtonBusinessModelsTaxModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'amount': value.amount,
        'value': value.value,
        'tax': value.tax,
    };
}

