/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class PayPhoneButtonBusinessModelsPrepareSaleModel {
    /**
    * Payment id generate
    */
    'paymentId'?: string;
    /**
    * Url for redirect and pay with PayPhone
    */
    'payWithPayPhone'?: string;
    /**
    * Url for redirect to PayPhone and pay only with your credit card
    */
    'payWithCard'?: string;
    'payWithPaymentCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "payWithPayPhone",
            "baseName": "payWithPayPhone",
            "type": "string",
            "format": ""
        },
        {
            "name": "payWithCard",
            "baseName": "payWithCard",
            "type": "string",
            "format": ""
        },
        {
            "name": "payWithPaymentCode",
            "baseName": "payWithPaymentCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsPrepareSaleModel.attributeTypeMap;
    }

    public constructor() {
    }
}

