/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PayPhoneButtonBusinessModelsLineItem } from './PayPhoneButtonBusinessModelsLineItem';
import {
    PayPhoneButtonBusinessModelsLineItemFromJSON,
    PayPhoneButtonBusinessModelsLineItemFromJSONTyped,
    PayPhoneButtonBusinessModelsLineItemToJSON,
} from './PayPhoneButtonBusinessModelsLineItem';
import type { PayPhoneISO8583ModelsPayPhoneBillTo } from './PayPhoneISO8583ModelsPayPhoneBillTo';
import {
    PayPhoneISO8583ModelsPayPhoneBillToFromJSON,
    PayPhoneISO8583ModelsPayPhoneBillToFromJSONTyped,
    PayPhoneISO8583ModelsPayPhoneBillToToJSON,
} from './PayPhoneISO8583ModelsPayPhoneBillTo';

/**
 * 
 * @export
 * @interface PayPhoneButtonBusinessModelsOrder
 */
export interface PayPhoneButtonBusinessModelsOrder {
    /**
     * 
     * @type {PayPhoneISO8583ModelsPayPhoneBillTo}
     * @memberof PayPhoneButtonBusinessModelsOrder
     */
    billTo?: PayPhoneISO8583ModelsPayPhoneBillTo;
    /**
     * 
     * @type {Array<PayPhoneButtonBusinessModelsLineItem>}
     * @memberof PayPhoneButtonBusinessModelsOrder
     */
    lineItems?: Array<PayPhoneButtonBusinessModelsLineItem>;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsOrder interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsOrder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsOrderFromJSON(json: any): PayPhoneButtonBusinessModelsOrder {
    return PayPhoneButtonBusinessModelsOrderFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'billTo': !exists(json, 'billTo') ? undefined : PayPhoneISO8583ModelsPayPhoneBillToFromJSON(json['billTo']),
        'lineItems': !exists(json, 'lineItems') ? undefined : ((json['lineItems'] as Array<any>).map(PayPhoneButtonBusinessModelsLineItemFromJSON)),
    };
}

export function PayPhoneButtonBusinessModelsOrderToJSON(value?: PayPhoneButtonBusinessModelsOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'billTo': PayPhoneISO8583ModelsPayPhoneBillToToJSON(value.billTo),
        'lineItems': value.lineItems === undefined ? undefined : ((value.lineItems as Array<any>).map(PayPhoneButtonBusinessModelsLineItemToJSON)),
    };
}

