/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayPhoneISO8583ModelsPayPhoneBillTo
 */
export interface PayPhoneISO8583ModelsPayPhoneBillTo {
    /**
     * 
     * @type {number}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    billToId?: number;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    address1?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    address2?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    locality?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof PayPhoneISO8583ModelsPayPhoneBillTo
     */
    ipAddress?: string;
}

/**
 * Check if a given object implements the PayPhoneISO8583ModelsPayPhoneBillTo interface.
 */
export function instanceOfPayPhoneISO8583ModelsPayPhoneBillTo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneISO8583ModelsPayPhoneBillToFromJSON(json: any): PayPhoneISO8583ModelsPayPhoneBillTo {
    return PayPhoneISO8583ModelsPayPhoneBillToFromJSONTyped(json, false);
}

export function PayPhoneISO8583ModelsPayPhoneBillToFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneISO8583ModelsPayPhoneBillTo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'billToId': !exists(json, 'billToId') ? undefined : json['billToId'],
        'address1': !exists(json, 'address1') ? undefined : json['address1'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'locality': !exists(json, 'locality') ? undefined : json['locality'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'ipAddress': !exists(json, 'ipAddress') ? undefined : json['ipAddress'],
    };
}

export function PayPhoneISO8583ModelsPayPhoneBillToToJSON(value?: PayPhoneISO8583ModelsPayPhoneBillTo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'billToId': value.billToId,
        'address1': value.address1,
        'address2': value.address2,
        'country': value.country,
        'state': value.state,
        'locality': value.locality,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'phoneNumber': value.phoneNumber,
        'email': value.email,
        'postalCode': value.postalCode,
        'customerId': value.customerId,
        'ipAddress': value.ipAddress,
    };
}

