/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayPhoneButtonBusinessModelsUserModel
 */
export interface PayPhoneButtonBusinessModelsUserModel {
    /**
     * User Document id
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsUserModel
     */
    documentId?: string;
    /**
     * User name
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsUserModel
     */
    name?: string;
    /**
     * User last name
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsUserModel
     */
    lastName?: string;
    /**
     * User email
     * @type {string}
     * @memberof PayPhoneButtonBusinessModelsUserModel
     */
    email?: string;
    /**
     * User phone numbers
     * @type {Array<string>}
     * @memberof PayPhoneButtonBusinessModelsUserModel
     */
    phoneNumbers?: Array<string>;
}

/**
 * Check if a given object implements the PayPhoneButtonBusinessModelsUserModel interface.
 */
export function instanceOfPayPhoneButtonBusinessModelsUserModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PayPhoneButtonBusinessModelsUserModelFromJSON(json: any): PayPhoneButtonBusinessModelsUserModel {
    return PayPhoneButtonBusinessModelsUserModelFromJSONTyped(json, false);
}

export function PayPhoneButtonBusinessModelsUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayPhoneButtonBusinessModelsUserModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'documentId') ? undefined : json['documentId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneNumbers': !exists(json, 'phoneNumbers') ? undefined : json['phoneNumbers'],
    };
}

export function PayPhoneButtonBusinessModelsUserModelToJSON(value?: PayPhoneButtonBusinessModelsUserModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentId': value.documentId,
        'name': value.name,
        'lastName': value.lastName,
        'email': value.email,
        'phoneNumbers': value.phoneNumbers,
    };
}

