/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsOrder } from './payPhoneButtonBusinessModelsOrder';

/**
* Model for accept the new sale request
*/
export class PayPhoneButtonBusinessModelsPrepareSaleRequestModel {
    /**
    * Response url for this transaction
    */
    'responseUrl': string;
    'transactionSummaryUrl'?: string;
    /**
    * 
    */
    'timeZone'?: number;
    /**
    * Store Latitude
    */
    'lat'?: string;
    /**
    * Store longitude
    */
    'lng'?: string;
    /**
    * Language for this transaction
    */
    'lang'?: string;
    /**
    * Reference for this transaction
    */
    'reference'?: string;
    /**
    * User Phone number (optional)
    */
    'phoneNumber'?: string;
    /**
    * User email (optional)
    */
    'email'?: string;
    /**
    * Parameter opcional No 3 (Optional)
    */
    'optionalParameter'?: string;
    /**
    * 
    */
    'documentId'?: string;
    /**
    * Url execute when user click in cancel payment before complete the payment process
    */
    'cancellationUrl'?: string;
    'amount': number;
    'amountWithTax'?: number;
    'amountWithoutTax'?: number;
    'manualTax'?: boolean;
    'tax'?: number;
    'service'?: number;
    'tip'?: number;
    'clientTransactionId': string;
    'storeId'?: string;
    'terminalId'?: string;
    'currency'?: string;
    'order'?: PayPhoneButtonBusinessModelsOrder;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "responseUrl",
            "baseName": "responseUrl",
            "type": "string"
        },
        {
            "name": "transactionSummaryUrl",
            "baseName": "transactionSummaryUrl",
            "type": "string"
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "number"
        },
        {
            "name": "lat",
            "baseName": "lat",
            "type": "string"
        },
        {
            "name": "lng",
            "baseName": "lng",
            "type": "string"
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "optionalParameter",
            "baseName": "optionalParameter",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "cancellationUrl",
            "baseName": "cancellationUrl",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountWithTax",
            "baseName": "amountWithTax",
            "type": "number"
        },
        {
            "name": "amountWithoutTax",
            "baseName": "amountWithoutTax",
            "type": "number"
        },
        {
            "name": "manualTax",
            "baseName": "manualTax",
            "type": "boolean"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "number"
        },
        {
            "name": "tip",
            "baseName": "tip",
            "type": "number"
        },
        {
            "name": "clientTransactionId",
            "baseName": "clientTransactionId",
            "type": "string"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "string"
        },
        {
            "name": "terminalId",
            "baseName": "terminalId",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "PayPhoneButtonBusinessModelsOrder"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsPrepareSaleRequestModel.attributeTypeMap;
    }
}

