/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PayPhoneButtonBusinessModelsRegionModel {
    /**
    * Region name
    */
    'name'?: string;
    /**
    * Phone region prefix number
    */
    'prefixNumber'?: number;
    /**
    * ISO code like \"EC\"
    */
    'iso'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "prefixNumber",
            "baseName": "prefixNumber",
            "type": "number"
        },
        {
            "name": "iso",
            "baseName": "iso",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsRegionModel.attributeTypeMap;
    }
}

