/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PayPhonePaymentButtonModelsLinkViewModel {
    /**
    * Transaction amount
    */
    'amount': number;
    /**
    * Transaction tax
    */
    'tax'?: number;
    /**
    * Transaction amount with tax
    */
    'amountWithTax'?: number;
    /**
    * Trasnaction amount without tax
    */
    'amountWithoutTax'?: number;
    /**
    * Service amount
    */
    'service'?: number;
    /**
    * Tip amount
    */
    'tip'?: number;
    /**
    * Currency to charge in ISO 4217 (USD)
    */
    'currency': string;
    /**
    * Reference describing the transaction MAX(50 characters)
    */
    'reference'?: string;
    /**
    * Transaction identifier Max(50)
    */
    'clientTransactionId': string;
    /**
    * Store identifier. It can be found in the developer\'s console
    */
    'storeId'?: string;
    /**
    * (Optional) Additional parameters, accept a json
    */
    'additionalData'?: string;
    /**
    * The link only can pay one time, the pay must be approved
    */
    'oneTime'?: boolean;
    /**
    * When the link is no longer available in hours
    */
    'expireIn'?: number;
    /**
    * Si aplica monto editable
    */
    'isAmountEditable'?: boolean;
    /**
    * Si es masivo o no
    */
    'isMassive'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        },
        {
            "name": "amountWithTax",
            "baseName": "amountWithTax",
            "type": "number"
        },
        {
            "name": "amountWithoutTax",
            "baseName": "amountWithoutTax",
            "type": "number"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "number"
        },
        {
            "name": "tip",
            "baseName": "tip",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "clientTransactionId",
            "baseName": "clientTransactionId",
            "type": "string"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "string"
        },
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "string"
        },
        {
            "name": "oneTime",
            "baseName": "oneTime",
            "type": "boolean"
        },
        {
            "name": "expireIn",
            "baseName": "expireIn",
            "type": "number"
        },
        {
            "name": "isAmountEditable",
            "baseName": "isAmountEditable",
            "type": "boolean"
        },
        {
            "name": "isMassive",
            "baseName": "isMassive",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PayPhonePaymentButtonModelsLinkViewModel.attributeTypeMap;
    }
}

