/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsTaxModel } from './payPhoneButtonBusinessModelsTaxModel';

export class PayPhoneButtonBusinessModelsSaleGetModelB {
    'email'?: string;
    'cardType'?: string;
    'clientUserId'?: string;
    'processor'?: string;
    'bin'?: string;
    'lastDigits'?: string;
    'deferredCode'?: string;
    'deferredMessage'?: string;
    'deferred'?: boolean;
    'cardBrandCode'?: string;
    'cardBrand'?: string;
    'amount'?: number;
    'clientTransactionId'?: string;
    'phoneNumber'?: string;
    'statusCode'?: number;
    'transactionStatus'?: string;
    'authorizationCode'?: string;
    'message'?: string;
    'messageCode'?: number;
    'transactionId'?: number;
    'document'?: string;
    'taxes'?: Array<PayPhoneButtonBusinessModelsTaxModel>;
    'currency'?: string;
    'optionalParameter1'?: string;
    'optionalParameter2'?: string;
    'optionalParameter3'?: string;
    'optionalParameter4'?: string;
    'storeName'?: string;
    'date'?: Date;
    'regionIso'?: string;
    'transactionType'?: string;
    'recap'?: string;
    'reference'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "cardType",
            "type": "string"
        },
        {
            "name": "clientUserId",
            "baseName": "clientUserId",
            "type": "string"
        },
        {
            "name": "processor",
            "baseName": "processor",
            "type": "string"
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "lastDigits",
            "baseName": "lastDigits",
            "type": "string"
        },
        {
            "name": "deferredCode",
            "baseName": "deferredCode",
            "type": "string"
        },
        {
            "name": "deferredMessage",
            "baseName": "deferredMessage",
            "type": "string"
        },
        {
            "name": "deferred",
            "baseName": "deferred",
            "type": "boolean"
        },
        {
            "name": "cardBrandCode",
            "baseName": "cardBrandCode",
            "type": "string"
        },
        {
            "name": "cardBrand",
            "baseName": "cardBrand",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "clientTransactionId",
            "baseName": "clientTransactionId",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number"
        },
        {
            "name": "transactionStatus",
            "baseName": "transactionStatus",
            "type": "string"
        },
        {
            "name": "authorizationCode",
            "baseName": "authorizationCode",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "messageCode",
            "baseName": "messageCode",
            "type": "number"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "number"
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "string"
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "Array<PayPhoneButtonBusinessModelsTaxModel>"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "optionalParameter1",
            "baseName": "optionalParameter1",
            "type": "string"
        },
        {
            "name": "optionalParameter2",
            "baseName": "optionalParameter2",
            "type": "string"
        },
        {
            "name": "optionalParameter3",
            "baseName": "optionalParameter3",
            "type": "string"
        },
        {
            "name": "optionalParameter4",
            "baseName": "optionalParameter4",
            "type": "string"
        },
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "regionIso",
            "baseName": "regionIso",
            "type": "string"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "string"
        },
        {
            "name": "recap",
            "baseName": "recap",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsSaleGetModelB.attributeTypeMap;
    }
}

