/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PayPhoneButtonBusinessModelsTaxModel {
    /**
    * Tax name
    */
    'name'?: string;
    /**
    * Tax amount charged the sum of value and tax field
    */
    'amount'?: number;
    /**
    * Tax value
    */
    'value'?: number;
    /**
    * Tax apply for current tax
    */
    'tax'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsTaxModel.attributeTypeMap;
    }
}

