/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsPassenger } from './payPhoneButtonBusinessModelsPassenger';

export class PayPhoneButtonBusinessModelsLineItem {
    'productName'?: string;
    'unitPrice'?: number;
    'quantity'?: number;
    'totalAmount'?: number;
    'taxAmount'?: number;
    'productSKU'?: string;
    'productDescription'?: string;
    'shippingDestinationTypes'?: string;
    'passenger'?: PayPhoneButtonBusinessModelsPassenger;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productName",
            "baseName": "productName",
            "type": "string"
        },
        {
            "name": "unitPrice",
            "baseName": "unitPrice",
            "type": "number"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "number"
        },
        {
            "name": "taxAmount",
            "baseName": "taxAmount",
            "type": "number"
        },
        {
            "name": "productSKU",
            "baseName": "productSKU",
            "type": "string"
        },
        {
            "name": "productDescription",
            "baseName": "productDescription",
            "type": "string"
        },
        {
            "name": "shippingDestinationTypes",
            "baseName": "shippingDestinationTypes",
            "type": "string"
        },
        {
            "name": "passenger",
            "baseName": "passenger",
            "type": "PayPhoneButtonBusinessModelsPassenger"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsLineItem.attributeTypeMap;
    }
}

