/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PayPhonePaymentButtonModelsConfirmSaleRequestModel {
    /**
    * Gets or sets the identifier.
    */
    'id'?: number;
    /**
    * Gets or sets the client tx identifier.
    */
    'clientTxId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "clientTxId",
            "baseName": "clientTxId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayPhonePaymentButtonModelsConfirmSaleRequestModel.attributeTypeMap;
    }
}

