/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsLineItem } from './payPhoneButtonBusinessModelsLineItem';
import { PayPhoneISO8583ModelsPayPhoneBillTo } from './payPhoneISO8583ModelsPayPhoneBillTo';

export class PayPhoneButtonBusinessModelsOrder {
    'billTo'?: PayPhoneISO8583ModelsPayPhoneBillTo;
    'lineItems'?: Array<PayPhoneButtonBusinessModelsLineItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billTo",
            "baseName": "billTo",
            "type": "PayPhoneISO8583ModelsPayPhoneBillTo"
        },
        {
            "name": "lineItems",
            "baseName": "lineItems",
            "type": "Array<PayPhoneButtonBusinessModelsLineItem>"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsOrder.attributeTypeMap;
    }
}

