/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsSale } from './payPhoneButtonBusinessModelsSale';

/**
* Cancellation model
*/
export class PayPhoneButtonBusinessModelsCancellationModel {
    /**
    * Cancellation identifier
    */
    'id'?: number;
    /**
    * Status code of cancellation
    */
    'statusCode'?: number;
    /**
    * Literal status of cancellation
    */
    'status'?: string;
    /**
    * Client transaction id
    */
    'clientTransactionId'?: string;
    'sale'?: PayPhoneButtonBusinessModelsSale;
    /**
    * Message for this annul
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "clientTransactionId",
            "baseName": "clientTransactionId",
            "type": "string"
        },
        {
            "name": "sale",
            "baseName": "sale",
            "type": "PayPhoneButtonBusinessModelsSale"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsCancellationModel.attributeTypeMap;
    }
}

