/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PayPhoneButtonBusinessModelsPrepareSaleModel {
    /**
    * Payment id generate
    */
    'paymentId'?: string;
    /**
    * Url for redirect and pay with PayPhone
    */
    'payWithPayPhone'?: string;
    /**
    * Url for redirect to PayPhone and pay only with your credit card
    */
    'payWithCard'?: string;
    'payWithPaymentCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentId",
            "baseName": "paymentId",
            "type": "string"
        },
        {
            "name": "payWithPayPhone",
            "baseName": "payWithPayPhone",
            "type": "string"
        },
        {
            "name": "payWithCard",
            "baseName": "payWithCard",
            "type": "string"
        },
        {
            "name": "payWithPaymentCode",
            "baseName": "payWithPaymentCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsPrepareSaleModel.attributeTypeMap;
    }
}

