/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Sale model to response
*/
export class PayPhoneButtonBusinessModelsSaleModel {
    /**
    * Identifier for current created transaction
    */
    'transactionId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsSaleModel.attributeTypeMap;
    }
}

