/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PayPhoneButtonBusinessModelsTaxModel } from './payPhoneButtonBusinessModelsTaxModel';

/**
* Sale get model
*/
export class PayPhoneButtonBusinessModelsSaleGetModel {
    /**
    * Customer email
    */
    'email'?: string;
    /**
    * Card type
    */
    'cardType'?: string;
    /**
    * External user identifier
    */
    'clientUserId'?: string;
    /**
    * Processor that served the request
    */
    'processor'?: string;
    /**
    * Card bin
    */
    'bin'?: string;
    /**
    * Últimos dígitos de la tarjeta
    */
    'lastDigits'?: string;
    /**
    * Deferred code
    */
    'deferredCode'?: string;
    /**
    * Deferred message
    */
    'deferredMessage'?: string;
    /**
    * Flag that indicate if the payment was deferred or not
    */
    'deferred'?: boolean;
    /**
    * Card brand code Example (Visa 50)
    */
    'cardBrandCode'?: string;
    /**
    * Card brand
    */
    'cardBrand'?: string;
    /**
    * Amount charged (Number)
    */
    'amount'?: number;
    /**
    * Client transaction id
    */
    'clientTransactionId'?: string;
    /**
    * Customer phone number
    */
    'phoneNumber'?: string;
    /**
    * Transaction status code Example(1)
    */
    'statusCode'?: number;
    /**
    * Transaction status Example(Canceled)
    */
    'transactionStatus'?: string;
    /**
    * Authorization code emiting by bank, this field have value is transaction status was approved
    */
    'authorizationCode'?: string;
    /**
    * Message for error
    */
    'message'?: string;
    /**
    * Message code for the reason why transaction not approved
    */
    'messageCode'?: number;
    /**
    * PayPhone transaction id
    */
    'transactionId'?: number;
    /**
    * Customer Document id
    */
    'document'?: string;
    /**
    * Taxes apply to current transaction
    */
    'taxes'?: Array<PayPhoneButtonBusinessModelsTaxModel>;
    /**
    * ISO code A of transaction currency
    */
    'currency'?: string;
    /**
    * Optional parameter 1
    */
    'optionalParameter1'?: string;
    /**
    * Optional parameter 2
    */
    'optionalParameter2'?: string;
    /**
    * Optional parameter 3
    */
    'optionalParameter3'?: string;
    /**
    * Optional parameter 4
    */
    'optionalParameter4'?: string;
    /**
    * Store name
    */
    'storeName'?: string;
    /**
    * Fecha en la que se realizo la transacción
    */
    'date'?: Date;
    /**
    * ISO code de la region de la tienda que recibió el pago
    */
    'regionIso'?: string;
    'transactionType'?: string;
    'recap'?: string;
    'reference'?: string;
    'canBypassRedirection'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "cardType",
            "type": "string"
        },
        {
            "name": "clientUserId",
            "baseName": "clientUserId",
            "type": "string"
        },
        {
            "name": "processor",
            "baseName": "processor",
            "type": "string"
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "lastDigits",
            "baseName": "lastDigits",
            "type": "string"
        },
        {
            "name": "deferredCode",
            "baseName": "deferredCode",
            "type": "string"
        },
        {
            "name": "deferredMessage",
            "baseName": "deferredMessage",
            "type": "string"
        },
        {
            "name": "deferred",
            "baseName": "deferred",
            "type": "boolean"
        },
        {
            "name": "cardBrandCode",
            "baseName": "cardBrandCode",
            "type": "string"
        },
        {
            "name": "cardBrand",
            "baseName": "cardBrand",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "clientTransactionId",
            "baseName": "clientTransactionId",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number"
        },
        {
            "name": "transactionStatus",
            "baseName": "transactionStatus",
            "type": "string"
        },
        {
            "name": "authorizationCode",
            "baseName": "authorizationCode",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "messageCode",
            "baseName": "messageCode",
            "type": "number"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "number"
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "string"
        },
        {
            "name": "taxes",
            "baseName": "taxes",
            "type": "Array<PayPhoneButtonBusinessModelsTaxModel>"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "optionalParameter1",
            "baseName": "optionalParameter1",
            "type": "string"
        },
        {
            "name": "optionalParameter2",
            "baseName": "optionalParameter2",
            "type": "string"
        },
        {
            "name": "optionalParameter3",
            "baseName": "optionalParameter3",
            "type": "string"
        },
        {
            "name": "optionalParameter4",
            "baseName": "optionalParameter4",
            "type": "string"
        },
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "regionIso",
            "baseName": "regionIso",
            "type": "string"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "string"
        },
        {
            "name": "recap",
            "baseName": "recap",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "canBypassRedirection",
            "baseName": "canBypassRedirection",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsSaleGetModel.attributeTypeMap;
    }
}

