/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PayPhoneButtonBusinessModelsUserModel {
    /**
    * User Document id
    */
    'documentId'?: string;
    /**
    * User name
    */
    'name'?: string;
    /**
    * User last name
    */
    'lastName'?: string;
    /**
    * User email
    */
    'email'?: string;
    /**
    * User phone numbers
    */
    'phoneNumbers'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumbers",
            "baseName": "phoneNumbers",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsUserModel.attributeTypeMap;
    }
}

