/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PayPhonePaymentButtonModelsCancellationSetByClientRequestModel,
  PayPhonePaymentButtonModelsCancellationSetRequestModel,
} from '../models/index';
import {
    PayPhonePaymentButtonModelsCancellationSetByClientRequestModelFromJSON,
    PayPhonePaymentButtonModelsCancellationSetByClientRequestModelToJSON,
    PayPhonePaymentButtonModelsCancellationSetRequestModelFromJSON,
    PayPhonePaymentButtonModelsCancellationSetRequestModelToJSON,
} from '../models/index';

export interface CancelSetRequest {
    model: PayPhonePaymentButtonModelsCancellationSetRequestModel;
}

export interface CancelSetByClientRequest {
    model: PayPhonePaymentButtonModelsCancellationSetByClientRequestModel;
}

/**
 * 
 */
export class CancelApi extends runtime.BaseAPI {

    /**
     * POST: Request cancel transaction
     */
    async cancelSetRaw(requestParameters: CancelSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.model === null || requestParameters.model === undefined) {
            throw new runtime.RequiredError('model','Required parameter requestParameters.model was null or undefined when calling cancelSet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Cancel`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayPhonePaymentButtonModelsCancellationSetRequestModelToJSON(requestParameters.model),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * POST: Request cancel transaction
     */
    async cancelSet(requestParameters: CancelSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.cancelSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST: Request cancel transaction by client transaction id
     */
    async cancelSetByClientRaw(requestParameters: CancelSetByClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.model === null || requestParameters.model === undefined) {
            throw new runtime.RequiredError('model','Required parameter requestParameters.model was null or undefined when calling cancelSetByClient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Cancel/client`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayPhonePaymentButtonModelsCancellationSetByClientRequestModelToJSON(requestParameters.model),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * POST: Request cancel transaction by client transaction id
     */
    async cancelSetByClient(requestParameters: CancelSetByClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.cancelSetByClientRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
