/* tslint:disable */
/* eslint-disable */
/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PayPhonePaymentButtonModelsCancellationSetByClientRequestModel,
  PayPhonePaymentButtonModelsCancellationSetRequestModel,
} from '../models/index';
import {
    PayPhonePaymentButtonModelsCancellationSetByClientRequestModelFromJSON,
    PayPhonePaymentButtonModelsCancellationSetByClientRequestModelToJSON,
    PayPhonePaymentButtonModelsCancellationSetRequestModelFromJSON,
    PayPhonePaymentButtonModelsCancellationSetRequestModelToJSON,
} from '../models/index';

export interface ReverseSetRequest {
    model: PayPhonePaymentButtonModelsCancellationSetRequestModel;
}

export interface ReverseSetByClientIdRequest {
    model: PayPhonePaymentButtonModelsCancellationSetByClientRequestModel;
}

/**
 * 
 */
export class ReverseApi extends runtime.BaseAPI {

    /**
     * POST: Reverse transaction
     */
    async reverseSetRaw(requestParameters: ReverseSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.model === null || requestParameters.model === undefined) {
            throw new runtime.RequiredError('model','Required parameter requestParameters.model was null or undefined when calling reverseSet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Reverse`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayPhonePaymentButtonModelsCancellationSetRequestModelToJSON(requestParameters.model),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * POST: Reverse transaction
     */
    async reverseSet(requestParameters: ReverseSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.reverseSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST: Reverse transaction by client transaction id
     */
    async reverseSetByClientIdRaw(requestParameters: ReverseSetByClientIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.model === null || requestParameters.model === undefined) {
            throw new runtime.RequiredError('model','Required parameter requestParameters.model was null or undefined when calling reverseSetByClientId.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Reverse/Client`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayPhonePaymentButtonModelsCancellationSetByClientRequestModelToJSON(requestParameters.model),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * POST: Reverse transaction by client transaction id
     */
    async reverseSetByClientId(requestParameters: ReverseSetByClientIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.reverseSetByClientIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
