/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Sale model to response
*/
export class PayPhoneButtonBusinessModelsSaleModel {
    /**
    * Identifier for current created transaction
    */
    'transactionId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsSaleModel.attributeTypeMap;
    }

    public constructor() {
    }
}

