/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class PayPhonePaymentButtonModelsConfirmSaleRequestModel {
    /**
    * Gets or sets the identifier.
    */
    'id'?: number;
    /**
    * Gets or sets the client tx identifier.
    */
    'clientTxId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "clientTxId",
            "baseName": "clientTxId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PayPhonePaymentButtonModelsConfirmSaleRequestModel.attributeTypeMap;
    }

    public constructor() {
    }
}

