/**
 * PayPhone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class PayPhoneButtonBusinessModelsRegionModel {
    /**
    * Region name
    */
    'name'?: string;
    /**
    * Phone region prefix number
    */
    'prefixNumber'?: number;
    /**
    * ISO code like \"EC\"
    */
    'iso'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "prefixNumber",
            "baseName": "prefixNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "iso",
            "baseName": "iso",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PayPhoneButtonBusinessModelsRegionModel.attributeTypeMap;
    }

    public constructor() {
    }
}

